/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaradiobtn;

import java.awt.Color;
import javax.swing.ButtonGroup;
import javax.swing.JRadioButton;

/**
 *
 * @author Vitor
 */
public class LayoutJogo extends javax.swing.JFrame {
    
    String[] questoes = {
        "Platão é quem fez a famosa frase “Penso, logo existo”?",
        "O Vaticano é o menor país do mundo?",
        "O número pi possui infinitas casas decimais?",
        "A tabela periódica possui 118 elementos?",
        "O fogo foi descoberto no período Paleolítico da história?",
        "O Monte Roraima é a montanha mais alta do Brasil?",
        "Em 1902 foi eleito o primeiro presidente do Brasil?",
        "Filantropo é a definição de uma pessoa que possui uma riqueza enorme?",
        "O chuveiro elétrico é uma invenção totalmente brasileira?",
        "O Japão é o país com a maior expectativa de vida no mundo?"
    };
    String[][] opcoes = {
        {"Verdadeiro", "Falso"},
        {"Falso","Verdadeiro"},
        {"Falso","Verdadeiro"},
        {"Falso","Verdadeiro"},
        {"Falso","Verdadeiro"},
        {"Verdadeiro", "Falso"},
        {"Verdadeiro", "Falso"},
        {"Verdadeiro", "Falso"},
        {"Falso","Verdadeiro"},
        {"Falso","Verdadeiro"}
    
    };
    int index = 0;
    int corretos = 0;
    
    ButtonGroup grupoBotoes = new ButtonGroup();

    
    public LayoutJogo() {
        initComponents();
        grupoBotoes.add(bt_True);
        grupoBotoes.add(bt_False);
        
        NextActionPerformed(null);
    }
    
    public void getSelecionaOpcao(JRadioButton rdbotao){
        
        System.out.println(rdbotao.getText());
        System.out.println(opcoes[index][1]);
        if(rdbotao.getText().equals(opcoes[index][1])){
            corretos++; 
        }
            
        index++;
        enabledBotao(false);
    
    }
    
    public void enabledBotao( boolean sim_nao){
        bt_True.setEnabled(sim_nao);
        bt_False.setEnabled(sim_nao);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Container = new javax.swing.JPanel();
        Question = new javax.swing.JLabel();
        bt_True = new javax.swing.JRadioButton();
        bt_False = new javax.swing.JRadioButton();
        Next = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        Container.setBackground(new java.awt.Color(204, 204, 204));

        Question.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Question.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Question.setText("Questão");

        javax.swing.GroupLayout ContainerLayout = new javax.swing.GroupLayout(Container);
        Container.setLayout(ContainerLayout);
        ContainerLayout.setHorizontalGroup(
            ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Question, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        ContainerLayout.setVerticalGroup(
            ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Question, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                .addContainerGap())
        );

        bt_True.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        bt_True.setText("   Verdadeiro");
        bt_True.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_TrueActionPerformed(evt);
            }
        });

        bt_False.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        bt_False.setText("       Falso");
        bt_False.setActionCommand("Falso");
        bt_False.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt_False.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_FalseActionPerformed(evt);
            }
        });

        Next.setText("PRÓXIMA");
        Next.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Next, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(bt_True, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                        .addComponent(bt_False, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_True, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_False, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(Next, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextActionPerformed
        if(Next.getText().equals("Reiniciar o Jogo")) {
            
            Next.setText("Próximo");
            Container.setBackground(new java.awt.Color(204,204,204));
            index = 0;
            corretos = 0;
        
        }
        
        if(index == questoes.length){
            
           Question.setText("Sua pontuação: " + corretos + "/" + questoes.length);
           if(corretos >= (float) questoes.length/2){
               Container.setBackground(Color.GREEN);
           }else{
               Container.setBackground(Color.RED);
               enabledBotao(true);
           }
           
           Next.setText("Reiniciar o Jogo");
           
        }else{
           enabledBotao(true);
           Question.setText(questoes[index]);
           bt_True.setText(opcoes[index][0]);
           bt_False.setText(opcoes[index][1]);
           
           if(index == questoes.length-1){
               Next.setText("Final, visualize seu resultado");  
           }
            
       
        }
        
    grupoBotoes.clearSelection();
        
    }//GEN-LAST:event_NextActionPerformed

    private void bt_TrueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_TrueActionPerformed
        getSelecionaOpcao(bt_True);
        
    }//GEN-LAST:event_bt_TrueActionPerformed

    private void bt_FalseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_FalseActionPerformed
        getSelecionaOpcao(bt_False);
    }//GEN-LAST:event_bt_FalseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LayoutJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LayoutJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LayoutJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LayoutJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LayoutJogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Container;
    private javax.swing.JButton Next;
    private javax.swing.JLabel Question;
    private javax.swing.JRadioButton bt_False;
    private javax.swing.JRadioButton bt_True;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
